### ISSUE TITLE
bower support?

### ISSUE THREAD

**Issue by divined** [x6doooo/generator-gulp-angular2#14]
Why bower file added, but bower files are not injected?

**Comment by ruffiem** [comment]
There's no support for bower dependencies at this time.

**Comment by ruffiem** [comment]
This injection uses the bower-main-files module and will fetch only the files declared in the bower.json's "main" array so if it does not take some file (example : css for bootstrap), you will have to edit the bower.json from the bower component.

**Comment by divined** [comment]
Thx

**Comment by BenevidesLecontes** [comment]
I tried bower, but inject task not working for bower components. What i'm missing? @divined did it work for you?

Here's my bower.json:
{
  "name": "package",
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "v4.0.0-alpha.2"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  }
}
